version: "2"

services:
  backend:
    image: docker.io/avinkavish/ghost-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
  realtime:
    image: docker.io/avinkavish/ghost-realtime:latest
    build:
      context: ./realtime
      dockerfile: Dockerfile.prod
